name: Kris Anaya 
url: https://www.linkedin.com/in/kris-anaya-96901699
description: A blog for my data days 

permalink: /:year/:month/:day/:title/
paginate: 10
markdown: kramdown

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
